import{S as h,i as y}from"./assets/vendor-5ObWk2rO.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();document.head.insertAdjacentHTML("beforeend",`<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital@0;1&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,500;1,500&display=swap" rel="stylesheet">`);const g="https://pixabay.com/api/",b="46106680-1f6bf9cc8c5ebc2359fb269e0",c=document.querySelector(".gallery"),l=document.querySelector(".btn"),L=document.querySelector(".container"),v=document.querySelector(".div-loader");function S(r){const s=new URLSearchParams({q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${g}?key=${b}&${s}`).then(o=>{if(!o.ok)throw new Error("Sorry, there are no images matching your search query. Please try again!");return o.json()})}function i(r){y.error({title:"Error",message:r})}function u(r){v.style.visibility=r?"visible":"hidden"}function w(r){r.preventDefault();const s=r.currentTarget,o=s.elements.query.value.trim();if(!o){i("Sorry, there are no images matching your search query. Please try again!");return}c.innerHTML="",u(!0),l.disabled=!0,S(o).then(e=>{if(e.hits.length===0){i("Sorry, there are no images matching your search query. Please try again!");return}const a=e.hits.map(n).join("");c.insertAdjacentHTML("beforeend",a),P.refresh(),s.reset()}).catch(e=>{i(e.message)}).finally(()=>{u(!1),l.disabled=!1});function n({webformatURL:e,largeImageURL:t,tags:a,likes:f,views:p,comments:m,downloads:d}){return`<li class="image">
        <a class = "gallery-link" href = "${e}">  
        <img src = "${t}" alt = "${a}" />
        </a>
        <div class = "card-body">   
          <p class="text">Likes <span class = "value">${f}</span></p>
          <p class="text">Views <span class = "value">${p}</span></p>
          <p class="text">Comments <span class = "value">${m}</span></p>
          <p class="text">Downloads <span class = "value">${d}</span></p>
          </div>
        </li>`}}const P=new h(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});L.addEventListener("submit",w);
//# sourceMappingURL=index.js.map
